<form method="post">
<div class="form-group">
	<label>Module Name</label>
	<input type="text" class="form-control input-sm" name="module_name" />
</div>
<div class="form-group">
	<label>Include Controller</label>
	<input type="checkbox" name="create_controller" />
</div>
<div class="form-group">
	<label>Controller Name</label> <small>(Leave empty to generate controller with module name)</small>
	<input type="text" class="form-control input-sm" name="controller_name" />
</div>
<input type="submit" class="btn btn-block btn-sm btn-primary" value="Generate Module" /> 
</form>